### PR TITLE
Issue 6

### LINKED ISSUE #6: Create new route `users/add/`
Create a POST API handler that takes in the required data based on on the objects in the users array, and add the new entry to the same said array as well.

### PR DESCRIPTION
**Pull request by romantic-sid**
create the post route.
Close #6 
Screenshot 2022-10-12 at 1 27 48 PM

### CODE REVIEW

**Comment by XDRAGON2002** [comment]
@romantic-sid you are also supposed to add the newly created entry to the users array and then call the `/users/` route to display all the entries in the users array to showcase that the new object has been successfully added.

Make the above mentioned changes and update your PR.

**Comment by romantic-sid** [comment]
Update the issue
Close #6
Screenshot 2022-10-12 at 4 30 22 PM

**Comment by XDRAGON2002** [comment]
@romantic-sid there are some more edits that need to be made.

**Comment by romantic-sid** [comment]
Plz check it out

**Comment by XDRAGON2002** [comment]
@romantic-sid remove the extra tab as mentioned above.

**Comment by XDRAGON2002** [comment]
LGTM!

**Pull request merged**
