### PR TITLE
added routes folder

### LINKED ISSUE #22: Make a proper folder structure for routes,middlewares etc.
Hey , @XDRAGON2002 , i would like to work on this issue , Can you assign this to me ?

### PR DESCRIPTION
**Pull request by ImAnshuJoshi**
@XDRAGON2002 , i have created a routes folder for the logic part of the route .
Please review it.
closes #22

### CODE REVIEW

**Comment by XDRAGON2002** [comment]
@ImAnshuJoshi 2 things,
- You need to resolve the merge conflicts
- Why have you added react-router-dom as a dependency in the backend package.json and package-lock.json?

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 i was just checking a few things thats why added those , removing them now and working on conflicts .

**Comment by ImAnshuJoshi** [comment]
@XDRAGON2002 , i have resolved all the conflicts and removed the unwanted dependencies.

**Comment by XDRAGON2002** [comment]
LGTM!

**Pull request merged**
