### PR TITLE
user/update/id route added

### PR DESCRIPTION
**Pull request by iamhariom0228**
Screenshot (591)
Screenshot (592)
hey @XDRAGON2002 , I  have added the update route . please check it out.

### CODE REVIEW

**Comment by XDRAGON2002** [comment]
@iamhariom0228 attach some screenshots of postman/thunderclient calling the api and showing that the results are actually being updated.

Also update the error message in the else block to something more generic than specifically pointing out that the gender attribute value is wrong.

**Comment by iamhariom0228** [comment]
Sure sir

**Comment by XDRAGON2002** [comment]
Also you have used the variable gen, replace that variable name with variable to keep it common throughout the codebase.

**Comment by iamhariom0228** [comment]
Ok sir

**Comment by iamhariom0228** [comment]
@XDRAGON2002  sir I have attached the screenshots for reference and  also changed the variable. Have a look..

**Comment by XDRAGON2002** [comment]
@iamhariom0228 Great job! LGTM!

**Pull request merged**
